### ISSUE TITLE
Do you really need all those usings?

### ISSUE THREAD

**Issue by incredibleLeitman** [milemihailov/SlotMachine#11]
https://github.com/milemihailov/SlotMachine/blob/0e8e7bff050e503dd2125c506b8b40fca9c1bd2a/SlotMachine/UiMethods.cs#L1-L8

Verify and clean your code before every commit, 
use Ctrl+K+D regularly and sort and remove your usings ☝️

**Comment by milemihailov** [comment]
is it okay if i enable this ? 
<img width="402" alt="image" src="https://github.com/milemihailov/SlotMachine/assets/92251917/a2ce075e-5240-47f6-ba0f-500ceb66f74a">

**Comment by incredibleLeitman** [comment]
I am not sure 🤔 
Where does this come from? xD

Usually you can right click on the using block and select "remove and sort usings" or use the keyboard shortcut for that

**Comment by milemihailov** [comment]
> is it okay if i enable this ? <img alt="image" width="402" src="https://user-images.githubusercontent.com/92251917/244316651-a2ce075e-5240-47f6-ba0f-500ceb66f74a.png">

its under tools --> options --> texteditor --> codecleanup
but i already removed unnesecary imports and formated the code
