### ISSUE TITLE
"row" variable is not really needed

### ISSUE THREAD

**Issue by incredibleLeitman** [milemihailov/SlotMachine#2]
https://github.com/milemihailov/SlotMachine/blob/671b4338749e11c50d67c528fc3071cda60b063d/SlotMachine/Program.cs#L34-L52

You only use this extra variable to print a newline after each line of numbers -> but you already use loop variables for lines and columns.

Here I would suggest that you also use proper loop variable names, "row" and "col" are very common in this use case as they help to easily identify the position of in the grid

**Comment by milemihailov** [comment]
i have done it in my last commit
