### ISSUE TITLE
Move value check lines to a static method

### ISSUE THREAD

**Issue by mayisa87** [milemihailov/SlotMachine#21]
https://github.com/milemihailov/SlotMachine/blob/dc586604a63cdac79933efde21b75d1a707c198c/SlotMachine/LogicMethods.cs#L69-L72

https://github.com/milemihailov/SlotMachine/blob/dc586604a63cdac79933efde21b75d1a707c198c/SlotMachine/LogicMethods.cs#L96-L99

Refactor to use a method called, like. Reason is simply, that you can later (next issue) refactor VerticalCheckForWin and HorizontalCheckForWin to one method called checkLinesForWin. 

public static bool valueMatch(int value1, int value2)
{
       return value1 == value2;    
 }

**Comment by milemihailov** [comment]
done in 22#

**Comment by milemihailov** [comment]
#22
