### ISSUE TITLE
Do you really need both waitFor methods?

### ISSUE THREAD

**Issue by mayisa87** [milemihailov/SlotMachine#27]
https://github.com/milemihailov/SlotMachine/blob/2f949b02c9fc659c412cbd0a6f53de053cb800d1/SlotMachine/UiMethods.cs#L161-L196

This two methods are both waiting for an int to be read from line, only difference the guided message shown.
You could try to remove waitForBet and use only waitForNum where you add an input parameter Options, so you can show the right guided messages based on your enum.

`public static int WaitForNum(Options inputOption)`

**Comment by mayisa87** [comment]
I don't know if you already know about the option of overloading methods? So you can have two methods, called the same, but with different input params?

![image](https://github.com/milemihailov/SlotMachine/assets/130921606/120f7a51-04a1-4136-adf8-da87d662ed26)

If you call `waitForNum` without parameter, it will internally call the method with Parameter `Options.Number. `

So you could also change your waitForBet Methode to have no parameter, and internally call in there
`  waitForNum(Options.Bet)`

And please check the XML Description of waitNum as it is still refering wage

**Comment by milemihailov** [comment]
i have no idea what i was thinking with two same functions :D however i erased one code still works but i didn't understood the overload methods thing if you could just give me some link where i can read more about how it works. thanks

**Comment by mayisa87** [comment]
I guess you wanted to have 2 methods, as `UiMethods.ShowGuideMessage(UiMethods.Options.Number);` should be called with different parameters? Now you only have one method waitForBet which will call ShowGuidedMessage always with Options.Number, also in case Bet or Wage. 
Now you are calling waitForBet, so maybe rename this method to "waitForNum".

If you want to have waitForNum to ones call ShowGuidedMessage with Options.Bet and once with Options.Wage etc, you could  do an overloading of method. Later on there will be maybe even better ways, but there are still videos left in course for you :)

[Overloading methods]((https://www.programiz.com/csharp-programming/method-overloading))
